models/Menu.py
from flask_sqlalchemy import SQLAlchemy
from datetime import datetime
from menu import db, login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Menu(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    day = db.Column(db.String(120), nullable=False)
    menu = db.Column(db.String(900000), nullable=False)
    created = db.Column(db.DateTime, nullable=False,
        default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)    

    def __repr__(self):
        return f"Post('{self.day}', '{self.menu}')"

models/User.py
from flask_sqlalchemy import SQLAlchemy
from menu import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password = db.Column(db.String(120), nullable=False)
    menu = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"User('{self.username}')"
        

forms/menu.py
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class MenuForm(FlaskForm):
    day = StringField('Dzień', validators=[DataRequired()])
    menu = TextAreaField('Menu', validators=[DataRequired()])
    submit = SubmitField('Generuj')

forms/user.py
from flask_wtf import FlaskForm
from wtforms import validators
from wtforms.fields.simple import PasswordField

from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired, Length


class AddForm(FlaskForm):
    username = StringField('Pracownik', validators=[DataRequired(), Length(min=1, max=128)])
    password = PasswordField('Hasło', validators=[DataRequired()])
    submit = SubmitField('Dodaj pracownika')


class LoginForm(FlaskForm):
    username = StringField('Pracownik', validators=[DataRequired()])
    password = PasswordField('Hasło', validators=[DataRequired()])
    submit = SubmitField('Zaloguj')
    

__init__.py
import os

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from menu.config import Config

db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)


    db.init_app(app)

    with app.app_context():
        db.create_all()

    login_manager.init_app(app)
    

    from menu.controllers import user
    app.register_blueprint(user.app)

    from menu.controllers import menu
    app.register_blueprint(menu.app)
    app.add_url_rule('/', endpoint='index')

    return app

controllers/menu.py
import pdfkit
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, make_response
)
from flask_login import current_user, login_required
from menu import db
from menu.models import Menu
from menu.forms.menu import MenuForm
from werkzeug.exceptions import abort


app = Blueprint('menu', __name__)


@app.route('/')
def index():
    menu = Menu.query.get_or_404(id)
    return render_template('menu/index.html', menus=menus)


@app.route('/add', methods=('GET', 'POST'))
@login_required
def add():
    form = MenuForm()
    if form.validate_on_submit():
        menu = Menu(day=form.day.data, menu=form.menu.data, author=current_user)
        db.session.add(menu)
        db.session.commit()
        flash('Dodano kartę menu')
        return redirect(url_for('menu.index'))

    return render_template('menu/add.html', title='Dodaj kartę menu', form=form)

@app.route('/generate/<int:id>', methods=('GET',))
def generate_pdf(id):
    menu = Menu.query.get_or_404(id)
    pdf = render_template('pdf/pdf.html', menu=menu)
    generate = pdfkit.from_string(pdf)

    run = make_response(generate)
    run.headers['Content-Type'] = 'application/pdf'
    run.headers['Content-Disposition'] = 'inline; filename=karta.pdf'
    return run

@app.route('/<int:id>')
def view(id):
    menu = Menu.query.get_or_404(id)
    return render_template('menu/view.html', menu=menu)


@app.route('/<int:id>/update', methods=('GET', 'POST'))
def update(id):
    menu = Menu.query.get_or_404(id)
    if form.validate_on_submit():
        menu.day = form.day.data
        menu.menu = form.menu.data
        db.session.commit()
        return redirect(url_for('menu.menu', id=id))
    
    return render_template('menu/update.html', menu=menu)


@app.route('/<int:id>/delete', methods=('POST',))
def delete(id):
    menu = Menu.query.get_or_404(id)
    db.session.delete(menu)
    db.session.commit()
    return redirect(url_for('menu.index'))

controllers/user.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from flask_login import login_user, current_user, logout_user, login_required
from menu import db
from menu.models import User
from menu.forms.user import (AddForm, LoginForm)
from werkzeug.security import check_password_hash, generate_password_hash


app = Blueprint('user', __name__, url_prefix=('/user'))

@app.route('/add', methods=('GET', 'POST'))
def register():
    form = AddForm()
    if form.validate_on_submit():
        pass_hash = generate_password_hash(form.password.data)
        user = User(username=form.username.data, password=pass_hash)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.login'))
    return render_template('user/add.html', title='Dodaj pracownika', form=form)

@app.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('index'))
        else:
            flash('Logowanie nie powiodło się')
    return render_template('user/login.html', title='Zaloguj się', form=form)

@app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %}</title>
<head>
<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>

<body class="d-flex flex-column h-100">
<main class="flex-shrink-0">
<div class="container">
  <ul>
    {% if g.user %}
      <li><span>{{ g.user.username }}</span>
      <li><a href="{{ url_for('user.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('user.register') }}">Add account</a>
      <li><a href="{{ url_for('user.login') }}">Login</a>
    {% endif %}
  </ul>


  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</div>
</main>

</body>

templates/menu/add.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Dodaj menu{% endblock %}</h1>
{% endblock %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
  <form method="post">
    {{ render_field(form.day) }}
    {{ render_field(form.menu) }}
    {{ render_field(form.submit) }}
  </form>
{% endblock %}

templates/menu/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Dostępne karty menu: {% endblock %}</h1>
  {% if g.user %}
    <a class="btn btn-success" href="{{ url_for('menu.add') }}">Create</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for menu in menus %}
    <article class="post">
      <header>
        <div>
          <h1><a href="{{ url_for('menu.view', id=menu['id']) }}">{{ menu['day'] }}</a></h1>
          <div class="about">{{ menu.username }} &bull; Dodano: {{ menu.created.strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user.id == menu.creator_id %}
          <a class="btn btn-primary" href="{{ url_for('menu.update', id=menu.id) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ menu.menu }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

templates/menu/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ menu.day }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
  <form method="post">
    {{ render_field(form.day) }}
    {{ render_field(form.menu) }}
    {{ render_field(form.submit) }}
  </form>
{% endblock %}

templates/menu/view.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %} Menu: {% endblock %}</h1>
{% endblock %}

{% block content %}
    <article class="post">
      <header>
        <div>
          <h1>{{ menu['day'] }}</h1>
          <div class="about">{{ menu.username}} &bull; Created: {{ menu.created.strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == menu.creator_id %}
          <a class="btn btn-primary" href="{{ url_for('tournament.update', id=tournament.id) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ menu.menu }}</p>
    </article>
      <hr>
{% endblock %}

templates/pdf/pdf.html
<b>Karta na dzień:</b> {{ menu.day }}

<p>{{ menu.menu }}</p>

templates/user/add.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Add account{% endblock %}</h1>
{% endblock %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
  <form method="post">
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ render_field(form.submit) }}
  </form>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Log In{% endblock %}</h1>
{% endblock %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
  <form method="post">
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ render_field(form.submit) }}
  </form>
{% endblock %}